let $RTP=split(&runtimepath, ',')[0]
let $VIMRC="$HOME/.vim/vimrc"

set nocompatible
set exrc
filetype indent plugin on
syntax on

let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()

" Quick search
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

" Status line
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'edkolev/tmuxline.vim'

" Coc
Plug 'neoclide/coc.nvim', {'branch': 'release'}

" Cpp
Plug 'alepez/vim-gtest'
Plug 'cdelledonne/vim-cmake'

" Git
Plug 'tpope/vim-fugitive'
Plug 'rbong/vim-flog'

" Linting/error highlighting
Plug 'dense-analysis/ale'
Plug 'ntpeters/vim-better-whitespace'

" Debugging
Plug 'puremourning/vimspector'

Plug 'mhinz/vim-signify'

Plug 'chrisbra/csv.vim'
Plug 'jiangmiao/auto-pairs'
Plug 'machakann/vim-highlightedyank'
Plug 'sheerun/vim-polyglot'
Plug 'ghifarit53/tokyonight-vim'
Plug 'tpope/vim-surround'

call plug#end()
