let $RTP=split(&runtimepath, ',')[0]
let $VIMRC="$HOME/.vim/vimrc"

set nocompatible
set exrc
filetype indent plugin on
syntax enable

let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

let maplocalleader = " "
let g:vimspector_enable_mappings = 'HUMAN'

call plug#begin()

Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

Plug 'vim-airline/vim-airline'
Plug 'edkolev/tmuxline.vim'

Plug 'puremourning/vimspector'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'sheerun/vim-polyglot'
Plug 'alepez/vim-gtest'
Plug 'ilyachur/cmake4vim'

Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-dispatch'

Plug 'machakann/vim-highlightedyank'

Plug 'morhetz/gruvbox'

call plug#end()

set termguicolors
set background=dark
set colorcolumn=80

let g:gruvbox_italic=1
let g:gitgutter_override_sign_column_highlight=1

colorscheme gruvbox

hi! link CocGitChangedSign GruvboxAquaSign
hi! link CocGitAddedSign GruvboxGreenSign
hi! link CocGitRemovedSign GruvboxRedSign 
hi! link CocGitTopRemovedSign GruvboxRedSign
hi! link CocGitChangeRemovedSign GruvboxAquaSign
hi! link FoldColumn Normal
