let $RTP=split(&runtimepath, ',')[0]
let $VIMRC="$HOME/.vim/vimrc"

set nocompatible

call plug#begin()

" Quick search
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'

" Status line 
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" Themes
Plug 'gruvbox-community/gruvbox'

" Coc
Plug 'neoclide/coc.nvim'
Plug 'neoclide/coc-snippets'
Plug 'neoclide/coc-tsserver'
Plug 'neoclide/coc-prettier'
Plug 'neoclide/coc-eslint'
Plug 'neoclide/coc-tslint'
Plug 'neoclide/coc-css'
Plug 'neoclide/coc-lists'
Plug 'neoclide/coc-highlight'

" C#
Plug 'OmniSharp/omnisharp-vim'

" Linting/error highlighting
Plug 'dense-analysis/ale'

Plug 'sirver/ultisnips'

call plug#end()